export const NEXT_PAGE= 'NEXT_PAGE';
export const PREV_PAGE ='PREV_PAGE';
export const PAGE_SELECTED='PAGE_SELECTED';
export const PAGE_DATA_REQUEST ='PAGE_DATA_REQUEST';
export const PAGE_DATA_SUCCESS = 'PAGE_DATA_SUCCESS';
export const PAGE_DATA_FAILURE ='PAGE_DATA_FAILURE';